// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/ip_access/check": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ip_access"
                ],
                "summary": "Check IP access decision",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IP address",
                        "name": "ip",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AccessDecision"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gintransport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/ip_access/lists": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ip_access"
                ],
                "summary": "List IP rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.IPRule"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gintransport.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ip_access"
                ],
                "summary": "Create IP rule",
                "parameters": [
                    {
                        "description": "Rule payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gintransport.CreateRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.IPRule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gintransport.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/gintransport.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/ip_access/lists/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ip_access"
                ],
                "summary": "Delete IP rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gintransport.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AccessDecision": {
            "type": "object",
            "properties": {
                "allowed": {
                    "type": "boolean"
                },
                "decision": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "matched_rule_id": {
                    "type": "string"
                },
                "matched_value": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "domain.IPRule": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/domain.ListType"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "domain.ListType": {
            "type": "string",
            "enum": [
                "allowlist",
                "denylist",
                "graylist"
            ],
            "x-enum-varnames": [
                "ListTypeAllow",
                "ListTypeDeny",
                "ListTypeGray"
            ]
        },
        "gintransport.CreateRuleRequest": {
            "type": "object",
            "required": [
                "type",
                "value"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "gintransport.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Proxy Service API",
	Description:      "Production-ready HTTP proxy service with IP access control.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
