spring.application.name=funeralService

spring.datasource.url=jdbc:postgresql://localhost:5432/funeral_service
spring.datasource.username=funeral_user
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration