spring.application.name=funeralService

spring.datasource.url=jdbc:postgresql://localhost:5432/funeral_service
spring.datasource.username=funeral_user
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


bank.service.url=http://localhost:8082
bank.receiver-card-number=9892115354974540
integration.bank.enabled=false

cemetery.service.url=http://localhost:8081
cemetery.service.login=funeral-service
cemetery.service.password=funeral123
integration.cemetery.enabled=false
